// Item icon mapping helper

// Auto-generated icon mapping from /public/assets folder
// Maps slugified item names to their corresponding image files
const autoGeneratedMapping = {
  "ancientartifact": "/assets/ancientartifact.png",
  "ancientsteel": "/assets/ancientsteel.svg",
  "ancientsword": "/assets/ancientsword.jpg",
  "animalhide": "/assets/animalhide.jpg",
  "arrow": "/assets/arrow.png",
  "bow": "/assets/bow.png",
  "bronzeaxe": "/assets/bronzeaxe.webp",
  "clay": "/assets/clay.png",
  "coal": "/assets/coal.png",
  "copperore": "/assets/copperore.png",
  "crystalshard": "/assets/crystalshard.png",
  "dragonamulet": "/assets/dragonamulet.jpeg",
  "enchantedgem": "/assets/enchantedgem.jpeg",
  "goldingot": "/assets/goldingot.jpeg",
  "goldore": "/assets/goldore.jpeg",
  "irondagger": "/assets/irondagger.jpg",
  "manadust": "/assets/manadust.jpg",
  "mithrilbar": "/assets/mithrilbar.png",
  "obsidian": "/assets/obsidian.jpeg",
  "pheonixblade": "/assets/pheonixblade.png",
  "phoenixblade": "/assets/pheonixblade.png", // Alternative spelling
  "sand": "/assets/sand.png",
  "steelingot": "/assets/steelingot.png",
  "stone": "/assets/stone.png",
  "stonearrow": "/assets/stonearrow.png",
  "stonespear": "/assets/stonespear.png",
  "stonesword": "/assets/stonesword.png",
  "tungstenore": "/assets/tungstenore.png",
  "waterflask": "/assets/waterflask.jpg",
  "wood": "/assets/wood.png",
};

function slugify(name){
  return String(name||'')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g,'_')
    .replace(/^_+|_+$/g,'');
}

export function getItemIcon(itemName) {
  const slug = slugify(itemName);
  
  // Try auto-generated mapping first
  if (autoGeneratedMapping[slug]) {
    return autoGeneratedMapping[slug];
  }
  
  // Try common variations
  const variations = [
    slug,
    slug.replace(/_/g, ''),
    itemName.toLowerCase().replace(/\s+/g, ''),
  ];
  
  for (const variant of variations) {
    if (autoGeneratedMapping[variant]) {
      return autoGeneratedMapping[variant];
    }
  }
  
  // Default fallback to PNG
  return `/assets/${slug}.png`;
}

export function getItemIconSync(itemName) {
  // Hardcoded mapping for immediate access (legacy items)
  const legacyMapping = {
    "Stone Sword": "/assets/stonesword.png",
    "Wood": "/assets/items/wood.svg",
    "Stone": "/assets/stone.png",
    "Iron Ore": "/assets/items/iron_ore.svg",
    "Crystal": "/assets/items/crystal.svg",
    "Dragon Scale": "/assets/items/dragon_scale.svg",
    "Iron Ingot": "/assets/items/iron_ingot.svg",
    "Wooden Sword": "/assets/items/wooden_sword.svg",
    "Stone Spear": "/assets/items/stone_spear.svg",
    "Iron Sword": "/assets/items/iron_sword.svg",
    "Fireball": "/assets/items/fireball.svg",
    "Dragon Blade": "/assets/items/dragon_blade.svg",
    "Leather Armor": "/assets/items/leather_armor.svg",
    "Iron Armor": "/assets/items/iron_armor.svg",
    "Steel Armor": "/assets/items/steel_armor.svg",
    "Bronze Armor": "/assets/items/bronze_armor.svg",
    "Dragon Armor": "/assets/items/dragon_armor.svg",
    "Phoenix Armor": "/assets/items/phoenix_armor.svg",
    "Frost Armor": "/assets/items/frost_armor.svg",
    "Lightning Armor": "/assets/items/lightning_armor.svg",
    "Shadow Cloak": "/assets/items/shadow_cloak.svg",
    "Holy Robe": "/assets/items/holy_robe.svg",
    "Stone Shield": "/assets/items/stone_shield.svg",
    "Iron Shield": "/assets/items/iron_shield.svg",
    "Steel Shield": "/assets/items/steel_shield.svg",
    "Dragon Shield": "/assets/items/dragon_shield.svg",
    "Magic Barrier": "/assets/items/magic_barrier.svg",
    "Blood Amulet": "/assets/items/blood_amulet.svg",
    "Frost Amulet": "/assets/items/frost_amulet.svg",
    "Flame Ring": "/assets/items/flame_ring.svg",
    "Lightning Ring": "/assets/items/lightning_ring.svg",
    "Star Crown": "/assets/items/star_crown.svg",
    "Dragon Sword": "/assets/items/dragon_sword.svg",
    "Phoenix Wand": "/assets/items/phoenix_wand.svg",
    "Holy Blade": "/assets/items/holy_blade.svg",
    "Demon Mace": "/assets/items/demon_mace.svg",
    "Star Staff": "/assets/items/star_staff.svg",
    "Frost Spear": "/assets/items/frost_spear.svg",
    "Thunder Bow": "/assets/items/thunder_bow.svg",
    "Blood Sword": "/assets/items/blood_sword.svg",
    "Sun Axe": "/assets/items/sun_axe.svg",
    "Shadow Wand": "/assets/items/shadow_wand.svg",
    "Dragon Hammer": "/assets/items/dragon_hammer.svg",
    "Celestial Armor": "/assets/items/celestial_armor.svg",
    "Eternal Blade": "/assets/items/eternal_blade.svg",
    "Chrono Staff": "/assets/items/chrono_staff.svg",
    "Infinity Relic": "/assets/items/infinity_relic.svg",
    // New assets mapping
    "Ancient Artifact": "/assets/ancientartifact.png",
    "Ancient Steel": "/assets/ancientsteel.svg",
    "Ancient Sword": "/assets/ancientsword.jpg",
    "Animal Hide": "/assets/animalhide.jpg",
    "Arrow": "/assets/arrow.png",
    "Bow": "/assets/bow.png",
    "Bronze Axe": "/assets/bronzeaxe.webp",
    "Clay": "/assets/clay.png",
    "Coal": "/assets/coal.png",
    "Copper Ore": "/assets/copperore.png",
    "Crystal Shard": "/assets/crystalshard.png",
    "Dragon Amulet": "/assets/dragonamulet.jpeg",
    "Enchanted Gem": "/assets/enchantedgem.jpeg",
    "Gold Ingot": "/assets/goldingot.jpeg",
    "Gold Ore": "/assets/goldore.jpeg",
    "Iron Dagger": "/assets/irondagger.jpg",
    "Mana Dust": "/assets/manadust.jpg",
    "Mithril Bar": "/assets/mithrilbar.png",
    "Obsidian": "/assets/obsidian.jpeg",
    "Phoenix Blade": "/assets/pheonixblade.png",
    "Sand": "/assets/sand.png",
    "Steel Ingot": "/assets/steelingot.png",
    "Steel Sword": "/assets/steelingot.png", // Reuse for steel sword
    "Stone Arrow": "/assets/stonearrow.png",
    "Stone Spear": "/assets/stonespear.png",
    "Tungsten Ore": "/assets/tungstenore.png",
    "Water Flask": "/assets/waterflask.jpg",
  };
  
  // Try exact match first
  if (legacyMapping[itemName]) {
    return legacyMapping[itemName];
  }
  
  // Try auto-generated mapping
  const slug = slugify(itemName);
  if (autoGeneratedMapping[slug]) {
    return autoGeneratedMapping[slug];
  }
  
  // Try without underscores
  const noUnderscores = slug.replace(/_/g, '');
  if (autoGeneratedMapping[noUnderscores]) {
    return autoGeneratedMapping[noUnderscores];
  }
  
  // Final fallback to PNG
  return `/assets/${slug}.png`;
}
